import { describe, it, expect } from "vitest";
import { analyze } from "../lib/har/analyze";
import { parseHar } from "../lib/har/parse";
import { toMarkdown } from "../lib/har/summary";

const HAR = JSON.stringify({
  log: {
    entries: [
      {
        startedDateTime: "2026-02-01T00:00:00.000Z",
        request: { method: "GET", url: "https://example.com/", headers: [], queryString: [], cookies: [] },
        response: { status: 200, content: { mimeType: "text/html", size: 1000 }, headers: [], cookies: [], _transferSize: 1000 },
        timings: { wait: 50, receive: 5 },
        cache: {},
      },
      {
        startedDateTime: "2026-02-01T00:00:00.060Z",
        request: { method: "GET", url: "https://cdn.other.com/a.js", headers: [], queryString: [], cookies: [] },
        response: { status: 500, content: { mimeType: "application/javascript", size: 2000 }, headers: [], cookies: [], _transferSize: 2000 },
        timings: { wait: 20, receive: 2 },
        cache: {},
      },
    ],
  },
});

describe("toMarkdown", () => {
  const a = analyze(parseHar(HAR));
  const md = toMarkdown("session.har", parseHar(HAR), a);

  it("renders the title with the report name", () => {
    expect(md).toContain("# Harbor report — session.har");
  });

  it("includes a summary list with the key metrics", () => {
    expect(md).toContain("Requests");
    expect(md).toContain("Transferred");
    expect(md).toContain("KB");
    expect(md).toContain("Errors");
    expect(md).toContain("Cache");
    // first/third split present
    expect(md).toContain("First party");
    expect(md).toContain("Third party");
  });

  it("surfaces the captured page URL from the parsed HAR", () => {
    expect(md).toContain(parseHar(HAR).pageUrl);
    expect(md).toContain("- Page: https://example.com/");
  });

  it("includes the core sections", () => {
    expect(md).toContain("## Slowest requests");
    expect(md).toContain("## Weight");
    expect(md).toContain("## Third parties");
  });

  it("ends with the no-upload footer", () => {
    expect(md).toContain("Generated by Harbor. Parsed entirely in the browser; nothing was uploaded.");
  });

  it("is deterministic: same input yields identical output", () => {
    const again = toMarkdown("session.har", parseHar(HAR), analyze(parseHar(HAR)));
    expect(again).toBe(md);
  });

  it("omits empty sections (no Privacy findings when privacy is empty)", () => {
    expect(a.privacy).toHaveLength(0);
    expect(md).not.toContain("## Privacy findings");
  });

  it("renders Privacy findings when present", () => {
    const leaky = JSON.stringify({
      log: {
        entries: [
          {
            startedDateTime: "2026-02-01T00:00:00.000Z",
            request: {
              method: "GET",
              url: "https://example.com/?token=abcdefghijklmnop",
              headers: [{ name: "Authorization", value: "Bearer abcdefghijklmnop" }],
              queryString: [{ name: "token", value: "abcdefghijklmnop" }],
              cookies: [],
            },
            response: { status: 200, content: { mimeType: "text/html", size: 100 }, headers: [], cookies: [], _transferSize: 100 },
            timings: { wait: 10, receive: 1 },
            cache: {},
          },
        ],
      },
    });
    const p = parseHar(leaky);
    const leakMd = toMarkdown("leak.har", p, analyze(p));
    expect(leakMd).toContain("## Privacy findings");
  });
});
