// ---------------------------------------------------------------------------
// summary.ts — render the deterministic Analysis as a shareable Markdown report.
// Pure: same input always yields the same document, so it's easy to unit-test
// and the page can offer a one-click download. No analysis happens here.
// ---------------------------------------------------------------------------

import type { Analysis } from "./analyze";
import type { ParseResult } from "./types";

function kb(bytes: number): string {
  return `${Math.round(bytes / 1024).toLocaleString()} KB`;
}

function ms(n: number): string {
  return `${Math.round(n).toLocaleString()} ms`;
}

/** Build a Markdown report from a parsed + analyzed HAR capture. */
export function toMarkdown(name: string, parse: ParseResult, a: Analysis): string {
  const s = a.summary;
  const L: string[] = [];

  L.push(`# Harbor report — ${name}`);
  L.push("");
  L.push(`- Page: ${parse.pageUrl || parse.primaryDomain}`);
  L.push(`- Requests: ${s.totalRequests.toLocaleString()}`);
  L.push(`- Transferred: ${kb(s.totalTransferBytes)}`);
  L.push(`- Load time: ${ms(s.pageLoadMs)}`);
  L.push(`- Time to first byte: ${ms(s.ttfbMs)}`);
  L.push(`- Errors: ${s.errors.toLocaleString()}`);
  L.push(`- Cache hit ratio: ${(s.cacheHitRatio * 100).toFixed(1)}%`);
  L.push(`- First party: ${kb(s.firstPartyBytes)}`);
  L.push(`- Third party: ${kb(s.thirdPartyBytes)}`);
  L.push("");

  if (a.waterfall.slowest.length) {
    L.push("## Slowest requests");
    L.push("");
    L.push("| Time | Status | Resource |");
    L.push("| ---: | ---: | --- |");
    for (const r of a.waterfall.slowest.slice(0, 10)) {
      L.push(`| ${ms(r.timings.total)} | ${r.status} | ${r.host}${r.path} |`);
    }
    L.push("");
  }

  if (a.weight.byCategory.length || a.weight.biggestOffenders.length) {
    L.push("## Weight");
    L.push("");
    if (a.weight.byCategory.length) {
      L.push(`Estimated compression savings: ${kb(a.weight.estimatedCompressionSavings)}`);
      L.push("");
      L.push("| Category | Requests | Bytes |");
      L.push("| --- | ---: | ---: |");
      for (const c of a.weight.byCategory.slice(0, 10)) {
        L.push(`| ${c.category} | ${c.count.toLocaleString()} | ${kb(c.bytes)} |`);
      }
      L.push("");
    }
    if (a.weight.biggestOffenders.length) {
      L.push("Biggest requests:");
      L.push("");
      for (const r of a.weight.biggestOffenders.slice(0, 10)) {
        L.push(`- ${kb(r.sizes.transferBytes)}: ${r.host}${r.path}`);
      }
      L.push("");
    }
  }

  if (a.thirdParties.length) {
    L.push("## Third parties");
    L.push("");
    L.push("| Domain | Category | Requests | Bytes |");
    L.push("| --- | --- | ---: | ---: |");
    for (const tp of a.thirdParties.slice(0, 10)) {
      L.push(`| ${tp.domain} | ${tp.category} | ${tp.requests.toLocaleString()} | ${kb(tp.bytes)} |`);
    }
    L.push("");
  }

  if (a.privacy.length) {
    L.push("## Privacy findings");
    L.push("");
    for (const f of a.privacy.slice(0, 15)) {
      L.push(`- **${f.severity}** [${f.kind}] ${f.title}: ${f.where} (${f.evidence})`);
    }
    L.push("");
  }

  L.push("---");
  L.push("_Generated by Harbor. Parsed entirely in the browser; nothing was uploaded._");
  return L.join("\n");
}
